### ISSUE TITLE
image refs on "Developing Developers" are broken

### ISSUE THREAD

**Issue by majewsky** [mfelleisen/web#1]
I was reading the [Developing Developers](https://felleisen.org/matthias/Thoughts/Developing_Developers.html) essay yesterday and therefore showed it to some colleagues today. In doing so, I discovered that the image references in the article are now broken. Just wanted to make you aware. This is probably related to https://github.com/mfelleisen/web/commit/d87a90b422c7fe3fecaaf8cf9f2323aec6ca2bf9 based on the timing.

**Comment by mfelleisen** [comment]
indeed.  i pushed the fix. Thanks.
